config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root "recipes#index"

  resources :recipes do
    resources :ingredient_for_recipes
  end
  
  resources :tags
  resources :ingredients

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :ingredient_for_recipes
  has_many :recipes, through: :ingredient_for_recipes

  validates :name, presence: true, uniqueness: true

  before_destroy :ingredient_in_use

  protected
  def ingredient_in_use
    recipes.empty?
  end
end

app/models/ingredient_for_recipe.rb
class IngredientForRecipe < ActiveRecord::Base
  belongs_to :ingredient
  belongs_to :recipe
  belongs_to :unit

  validates :amount, presence: true
  validates :amount, presence: true, numericality: { greater_than: 0, less_than:1000 }
  validates :ingredient_id, uniqueness: { scope: :recipe_id }

  def name
    ingredient.name
  end

  def amount_with_unit
    "#{amount} #{unit.name}"
  end

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  acts_as_taggable

  has_attached_file :picture, :styles => { :medium => "400x400>", :thumb => "150x150>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

  has_many :ingredient_for_recipes, dependent: :destroy
  has_many :ingredients, through: :ingredient_for_recipes
  belongs_to :user

  validates :name, presence: true, uniqueness: true, length: { maximum: 80 }
  validates :description, presence: true
  validates :directions, presence: true
  validates_attachment :picture, size: { :in => 0..1.megabytes }

  def self.tagged_or_all(tag=nil)
    recipes = tagged_with tag
    recipes = all if recipes.blank?
    recipes
  end
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  has_many :ingredients_for_recipes

  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :recipes

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
      data = access_token.info
      user = User.where(:email => data["email"]).first
      user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource_or_scope)
    recipes_path
  end

  def after_sign_out_path_for(resource_or_scope)
    recipes_path
  end
end

app/controllers/ingredient_for_recipes_controller.rb
class IngredientForRecipesController < ApplicationController
  before_action :set_recipe
  before_action :set_ingredient_for_recipe, only: [:show, :edit, :update, :destroy]

  def index
    @ingredient_for_recipe = @recipe.ingredient_for_recipes.all
  end

  def new
    @ingredient_for_recipe = @recipe.ingredient_for_recipes.new
  end

  def edit
  end

  def create
    @ingredient_for_recipe = @recipe.ingredient_for_recipes.new(ingredient_for_recipe_params)
      if @ingredient_for_recipe.save
        redirect_to recipe_ingredient_for_recipes_path(@recipe)
      else
        render 'new'
      end
  end

  def update
    if @ingredient_for_recipe.update(ingredient_for_recipe_params)
      redirect_to recipe_ingredient_for_recipes_path(@recipe)
    else
      render 'edit'
    end
  end

  def destroy
    @ingredient_for_recipe.destroy
    redirect_to recipe_ingredient_for_recipes_path(@recipe)
  end

  private

    def set_recipe
      @recipe = Recipe.find(params[:recipe_id])
    end

    def set_ingredient_for_recipe
      @ingredient_for_recipe = @recipe.ingredient_for_recipes.find(params[:id])
    end

    def ingredient_for_recipe_params
      params.require(:ingredient_for_recipe).permit(:ingredient_id, :recipe_id, :unit_id, :amount)
    end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

  before_action :set_ingredient, only: [:show, :edit, :update, :destroy]


  def index
    @ingredient = Ingredient.all
    @tags = ActsAsTaggableOn::Tag.all
  end

  def new
    session['back_to'] = request.referer
    @ingredient = Ingredient.new
  end

  def edit
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
      if @ingredient.save
        r = session['back_to']
        session.delete('back_to')
        redirect_to r || ingredients_path
      else
        render 'new'
      end
  end

  def update
    if @ingredient.update(ingredient_params)
      redirect_to ingredients_path
    else
      render 'edit'
    end
  end

  def destroy
    @ingredient.destroy
    redirect_to ingredients_path
  end

  private

    def set_ingredient
      @ingredient = Ingredient.find(params[:id])
    end

    def ingredient_params
      params.require(:ingredient).permit(:name)
    end



end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :set_tags_for_select, only: [:new, :create]
  before_filter :authenticate_user!, only: [:new, :edit, :update, :destroy]

  def index
    if params[:search]
      @recipe = Recipe.where(["name LIKE ? OR description LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%"])
    else 
      @recipe = Recipe.tagged_or_all(params[:tag])
    end
    @tags = ActsAsTaggableOn::Tag.all
  end

  def search
    render :text => @recipe.map(&:name).join(",")
  end

  def show
  end

  def new
    @recipe = Recipe.new
  end

  def edit
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
      if @recipe.save
        redirect_to @recipe
      else
        render 'new'
      end
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render 'edit'
    end
  end

  def destroy
    @recipe.destroy
    redirect_to recipes_path
  end

  private

    def set_tags_for_select
      @tags = ActsAsTaggableOn::Tag.all.map(&:name).to_json
    end

    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    def recipe_params
      params.require(:recipe).permit(:name, :description, :directions,
                                     :servings, :user_id, :vegan, :tag_list, :picture)
    end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  ActsAsTaggableOn.remove_unused_tags = true

  before_action :set_tag, only: [:show]

  def show
  end

private
    def set_tag
      @tag = ActsAsTaggableOn::Tag.find(params[:id])
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)
      if @user && @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredient_for_recipes_helper.rb
module IngredientForRecipesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
  def show_ingredient(ingredient_for_recipe)
    "#{ingredient_for_recipe.name} #{ingredient_for_recipe.amount_with_unit}"  
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/ingredient_for_recipes/_form.html.erb
  <%= simple_form_for([@recipe, @ingredient_for_recipe]) do |f| %>
    <%= f.input :amount %>
    <%= f.association :ingredient %>
    <%= f.association :unit %>
    <%= f.submit %>
  <% end %>
<br>
<%= link_to "Need more ingredients?", new_ingredient_path, class: "btn btn-default" %>

app/views/ingredient_for_recipes/edit.html.erb
<h1>Edit Ingredients For Recipes</h1>

<%= render 'form' %>

app/views/ingredient_for_recipes/index.html.erb
<h1> <%= "#{@recipe.name} ingredients" %> </h1>


<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
         <th>Ingredient</th>
         <th>Amount</th>
         <th>Unit</th>
         <th>Edit</th>
         <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @ingredient_for_recipe.each do |item| %>
       <tr>
        <td><%= item.ingredient.name %></td>
        <td><%= item.amount %></td>
        <td><%= item.unit.name %></td>
        <td><%= link_to "Edit", edit_recipe_ingredient_for_recipe_path(@recipe, item)%></td>
        <td><%= link_to "Delete", [@recipe, item], method: :delete %></td>
       </tr>
      <% end %>
      </tbody>
  </table>
</div>

<%= link_to "Go Home", root_path, class: "btn btn-default" %>
<%= link_to "Add more ingredients", new_recipe_ingredient_for_recipe_path(@recipe), class: "btn btn-default" %>

app/views/ingredient_for_recipes/new.html.erb
<div class = "container">
  <h1>Ingredients For Recipes</h1>
</div>

<%= render 'form' %>
<p></p>
<%= link_to "Recipe Ingredients", recipe_ingredient_for_recipes_path(@recipe), class: "btn btn-default" %>

app/views/ingredients/_form.html.erb
<%= simple_form_for(@ingredient, html: {class: "form-horizontal"}) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/ingredients/edit.html.erb
<div class = "container">
  <h1><%= "Edit #{@ingredient.name}" %></h1>
  <%= render 'form' %>
</div>

app/views/ingredients/index.html.erb
<h1> Ingredients: </h1>


<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
         <th>Name</th>
         <th>Edit</th>
         <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @ingredient.each do |ingredient| %>
       <tr>
        <td><%= ingredient.name %></td>
        <td><%= link_to "Edit", edit_ingredient_path(ingredient) %></td>
        <td><%= link_to "Delete", ingredient, method: :delete %></td>
       </tr>
      <% end %>
      </tbody>
  </table>
</div>

<%= link_to "Go Home", root_path, class: "btn btn-default" %>
<%= link_to "Need more?", new_ingredient_path, class: "btn btn-default" %>

app/views/ingredients/new.html.erb
<div class = "container">

  <h1>New Ingredient</h1>

  <%= render 'form' %>
</div>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CookBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="UTF-8">
</head>
<body>
  <div class="container">

  <div id="user_nav">
    <% if user_signed_in? %>
      Logged in as <%= current_user.email %>. Not you?
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> or
      <%= link_to "Login", new_user_session_path %>
      <% if false %>
      <% # link_to "Login with Google", user_omniauth_authorize_path(:google) %>
      <% end %>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </div>

  <h1>CookBook Rules</h1>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <div class = "navbar-brand"><%= link_to "Home", recipes_path %></div>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class = "active"> <%= link_to "New Recipe", new_recipe_path %> </li>
 
        </ul>
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <%= form_tag recipes_path, :method => :get do %>
              <p>
                <%= text_field_tag :search, params[:search] %>
                <%= submit_tag "Search", :name => nil %>
              </p>
            <% end %>
        </form>
      </div>
    </div>
  </nav>

    <%= yield %>

</div>
</body>
</html>

app/views/recipes/_form.html.erb
<%= hidden_field_tag 'tag_list', @tags, id: 'tag_list' %>

<%= simple_form_for(@recipe, html: {multipart: true}) do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :servings, label: "Servings:" %>
  <%= f.input :vegan, label: "Vegan?" %>
  <%= f.input :directions %>
  <%= f.input :tag_list, placeholder: "       " %>
  <%= f.input :picture %>
  <%= f.button :submit %>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>

<%= render 'form' %>

app/views/recipes/index.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col-sm-8">
      <ul class = "list-unstyled recipe-list">
        <% @recipe.each do |recipe| %>
          <li class = "recipe">
            <div class = "col-sm-3">
              <%= image_tag recipe.picture.url(:thumb) %>
            </div>
            <div class = "col-sm-9">
              <h4><%= link_to recipe.name, recipe %></h4>
              <div>
                <p><%= recipe.description %></p>
              </div>
              <p class="text-muted">Posted by <%= recipe.user.email %> </p>
              <div>
                <% recipe.tags.each do |tag| %>
                  <%= link_to tag.name, recipes_path(:tag => tag.name), class: 'label label-primary' %>
                <% end %>
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
    <div class = "col-sm-4">
      <h2>Tags:</h2>
      <ul class = "list-unstyled">
        <% @tags.all.each do |tag| %>
          <li>
            <%= link_to tag.name, recipes_path(:tag => tag.name), class: 'label label-primary'  %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="conatiner">

  <h1>New Recipe</h1>

  <%= render 'form' %>
</div>

app/views/recipes/show.html.erb
<div class="container">
  <div class="col-sm-12">
    <h1><%= @recipe.name %></h1>
  </div>

  <div class="col-sm-12">
    <div class="col-sm-5">
      <%= image_tag @recipe.picture.url(:medium) %>
    </div>
    <div class="col-sm-7">
      <strong> Ingredients: </strong>
      <ul>
        <% @recipe.ingredient_for_recipes.each do |ingredient| %>
          <li><%= show_ingredient(ingredient) %></li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="col-sm-12">
    <div class="col-sm-5">
      <strong> Description: </strong>
      <%= @recipe.description %>
    </div>
    <div class="col-sm-7">
      <strong> Directions: </strong>
      <%= @recipe.directions %>
    </div>
  </div>
</div>

<div class="col-sm-12"> 
<p>
  <strong>Servings: </strong>
  <%= @recipe.servings %>
</p>

<p>
  <strong>Vegan will be happy: </strong>
  <%= @recipe.vegan %>
</p>

<%= link_to "Add Ingredients", new_recipe_ingredient_for_recipe_path(@recipe), class: "btn btn-default" %>
<%= link_to "Edit", edit_recipe_path(@recipe), class: "btn btn-default" %>
<%= link_to "Delete", @recipe, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
<%= link_to "Go Home", root_path, class: "btn btn-default" %>
</div>